#!/usr/bin/env python3
"""
DataBridgeService auth token test.

Verifies that the Android service correctly rejects connections without
a valid session token and (optionally) accepts connections with one.

Usage:
  python3 test_auth.py                        # tests rejection only
  python3 test_auth.py -s SERIAL              # target a specific device
  python3 test_auth.py --token TOKEN          # also test the positive case
  python3 test_auth.py -s SERIAL --token T    # both

The token is the 32-char hex value generated by the Mac app on each
connection (UUID without hyphens). You can find it in the macOS app's
debug log panel — look for "start-foreground-service ... session_token".
"""

import argparse
import json
import socket
import subprocess
import sys
import time

HOST = "127.0.0.1"
PORT = 27184
RECV_TIMEOUT = 2.5   # seconds to wait for a response line
REJECT_TIMEOUT = 1.5 # seconds to wait before declaring a connection closed

GREEN  = "\033[32m"
RED    = "\033[31m"
YELLOW = "\033[33m"
RESET  = "\033[0m"
BOLD   = "\033[1m"

def ok(msg):  print(f"  {GREEN}PASS{RESET}  {msg}")
def fail(msg): print(f"  {RED}FAIL{RESET}  {msg}")
def info(msg): print(f"  {YELLOW}INFO{RESET}  {msg}")


# ── ADB forward ──────────────────────────────────────────────────────────────

def setup_forward(serial):
    args = ["adb"] + (["-s", serial] if serial else []) + ["forward", "tcp:27184", "tcp:27184"]
    r = subprocess.run(args, capture_output=True, text=True)
    return r.returncode == 0, r.stderr.strip()


# ── Low-level TCP helpers ─────────────────────────────────────────────────────

class BridgeConn:
    """A raw TCP connection to the DataBridgeService."""

    def __init__(self):
        self.sock = None

    def connect(self):
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.settimeout(RECV_TIMEOUT)
        self.sock.connect((HOST, PORT))

    def send(self, obj):
        line = json.dumps(obj) + "\n"
        self.sock.sendall(line.encode())

    def recv_line(self, timeout=None):
        """Return the next newline-delimited JSON line, or None on timeout/close."""
        self.sock.settimeout(timeout or RECV_TIMEOUT)
        buf = b""
        try:
            while b"\n" not in buf:
                chunk = self.sock.recv(4096)
                if not chunk:
                    return None  # connection closed by remote
                buf += chunk
            return buf.split(b"\n")[0].decode(errors="replace")
        except (socket.timeout, ConnectionResetError, OSError):
            return None

    def is_closed(self, timeout=REJECT_TIMEOUT):
        """Return True if the service closed the connection within `timeout` seconds."""
        self.sock.settimeout(timeout)
        try:
            data = self.sock.recv(1)
            return data == b""  # EOF = closed
        except socket.timeout:
            return False  # still open, just quiet
        except (ConnectionResetError, OSError):
            return True   # reset = closed

    def close(self):
        if self.sock:
            try: self.sock.close()
            except: pass
            self.sock = None


# ── Individual test cases ─────────────────────────────────────────────────────

def test_no_auth():
    """Skip auth entirely — send ping directly as the first message."""
    c = BridgeConn()
    try:
        c.connect()
        c.send({"type": "ping"})
        closed = c.is_closed()
        if closed:
            ok("No-auth ping rejected — connection closed by service")
            return True
        else:
            # If it got a pong, auth is not enforced
            line = c.recv_line(timeout=0.5)
            if line and "pong" in line:
                fail("No-auth ping got a pong response — auth NOT enforced")
            else:
                fail("Connection stayed open without auth (service did not reject)")
            return False
    except ConnectionRefusedError:
        fail("Connection refused — is the service running? Run the Mac app first.")
        return None
    except Exception as e:
        fail(f"Unexpected error: {e}")
        return None
    finally:
        c.close()


def test_wrong_token():
    """Send an auth message with a clearly wrong token, then ping."""
    c = BridgeConn()
    try:
        c.connect()
        c.send({"type": "auth", "token": "00000000000000000000000000000000"})
        c.send({"type": "ping"})
        closed = c.is_closed()
        if closed:
            ok("Wrong-token connection rejected — connection closed by service")
            return True
        else:
            line = c.recv_line(timeout=0.5)
            if line and "pong" in line:
                fail("Wrong-token ping got a pong — auth NOT enforced")
            else:
                fail("Connection stayed open with wrong token")
            return False
    except ConnectionRefusedError:
        fail("Connection refused — service not reachable.")
        return None
    except Exception as e:
        fail(f"Unexpected error: {e}")
        return None
    finally:
        c.close()


def test_malformed_auth():
    """Send garbage as the first line."""
    c = BridgeConn()
    try:
        c.connect()
        c.sock.sendall(b"not json at all\n")
        closed = c.is_closed()
        if closed:
            ok("Malformed first line rejected — connection closed by service")
            return True
        else:
            fail("Malformed first line: connection stayed open")
            return False
    except ConnectionRefusedError:
        fail("Connection refused.")
        return None
    except Exception as e:
        fail(f"Unexpected error: {e}")
        return None
    finally:
        c.close()


def test_valid_token(token):
    """Send the correct token and verify we get a pong response."""
    c = BridgeConn()
    try:
        c.connect()
        c.send({"type": "auth", "token": token})
        c.send({"type": "ping"})
        line = c.recv_line()
        if line is None:
            fail(f"Valid token sent but connection was closed (token may be stale or wrong)")
            return False
        try:
            obj = json.loads(line)
            if obj.get("type") == "pong":
                ok(f"Valid token accepted — got pong response")
                return True
            else:
                fail(f"Got unexpected response: {line[:120]}")
                return False
        except json.JSONDecodeError:
            fail(f"Got non-JSON response: {line[:120]}")
            return False
    except ConnectionRefusedError:
        fail("Connection refused.")
        return None
    except Exception as e:
        fail(f"Unexpected error: {e}")
        return None
    finally:
        c.close()


def test_replay_after_reject():
    """After a rejected connection, a second connection with the wrong token is also rejected."""
    c = BridgeConn()
    try:
        c.connect()
        c.send({"type": "auth", "token": "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa1"})
        c.is_closed()
    except: pass
    finally:
        c.close()

    time.sleep(0.2)  # brief pause to let service reset

    c2 = BridgeConn()
    try:
        c2.connect()
        c2.send({"type": "auth", "token": "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbb2"})
        closed = c2.is_closed()
        if closed:
            ok("Second wrong-token attempt also rejected — no bypass via reconnect")
            return True
        else:
            fail("Second wrong-token attempt was NOT rejected")
            return False
    except ConnectionRefusedError:
        fail("Connection refused on second attempt.")
        return None
    except Exception as e:
        fail(f"Unexpected error: {e}")
        return None
    finally:
        c2.close()


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-s", "--serial", metavar="SERIAL",
                        help="ADB device serial (omit for single connected device)")
    parser.add_argument("--token", metavar="TOKEN",
                        help="32-char hex session token from the Mac app (enables positive test)")
    args = parser.parse_args()

    print(f"\n{BOLD}DataBridgeService Auth Test{RESET}")
    print("─" * 44)

    # Set up ADB forward
    print("\nSetting up ADB forward tcp:27184…")
    ok_fwd, err = setup_forward(args.serial)
    if not ok_fwd:
        fail(f"adb forward failed: {err or '(no output)'}")
        print("\nMake sure the device is connected via USB and the Mac app has been opened at least once.")
        sys.exit(1)
    ok("adb forward tcp:27184 tcp:27184 ready")

    print("\n── Rejection tests ──────────────────────────────────────────────")

    results = []
    results.append(("No auth (ping as first message)",    test_no_auth()))
    results.append(("Wrong token",                         test_wrong_token()))
    results.append(("Malformed first line",                test_malformed_auth()))
    results.append(("Replay: second wrong-token attempt",  test_replay_after_reject()))

    if args.token:
        print("\n── Positive test (token provided) ───────────────────────────────")
        results.append(("Valid token accepted",            test_valid_token(args.token)))

    # Summary
    print("\n── Summary ──────────────────────────────────────────────────────")
    passed  = sum(1 for _, r in results if r is True)
    failed  = sum(1 for _, r in results if r is False)
    skipped = sum(1 for _, r in results if r is None)

    for name, result in results:
        icon = f"{GREEN}✓{RESET}" if result is True else f"{RED}✗{RESET}" if result is False else f"{YELLOW}–{RESET}"
        print(f"  {icon}  {name}")

    print()
    if failed == 0 and skipped == 0:
        print(f"{GREEN}{BOLD}All {passed} tests passed.{RESET} Auth is working correctly.")
    elif failed > 0:
        print(f"{RED}{BOLD}{failed} test(s) failed.{RESET} Auth may not be enforced — check the Android build.")
    else:
        print(f"{YELLOW}Skipped {skipped} test(s){RESET} (service unreachable). Is the device connected and the app open?")

    if not args.token:
        print(f"\n{YELLOW}Tip:{RESET} Run with --token TOKEN to also verify that a valid token IS accepted.")
        print("     Find the token in the Mac app's log panel (look for 'session_token' in the adb output).")

    print()
    sys.exit(0 if failed == 0 else 1)


if __name__ == "__main__":
    main()
